# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_v_poisgamma_cpp <- function(v, logz, lambda, X_z, beta_theta, u, beta_z, beta0, r_nb, mu, lambda_ijk, c_imk, delta, gamma, sigma, sigma_gamma, M_site, X_w, beta_w, K, emptySites) {
    .Call(`_functionsForForeach_update_v_poisgamma_cpp`, v, logz, lambda, X_z, beta_theta, u, beta_z, beta0, r_nb, mu, lambda_ijk, c_imk, delta, gamma, sigma, sigma_gamma, M_site, X_w, beta_w, K, emptySites)
}

update_delta_c_d_rjmcmc <- function(y, v, lambda, r_nb, M_site, K, lambdatilde, mu0, n0, pi0, u, logz, X_w, beta_w, sigma, mu, sigma_gamma, v_sd, p11, p10, theta11, theta10, emptySites) {
    .Call(`_functionsForForeach_update_delta_c_d_rjmcmc`, y, v, lambda, r_nb, M_site, K, lambdatilde, mu0, n0, pi0, u, logz, X_w, beta_w, sigma, mu, sigma_gamma, v_sd, p11, p10, theta11, theta10, emptySites)
}

